version: '3.7'

services:     
  mariadb:
    container_name: web-mariadb-2
    hostname: mariadb
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 11_WebApplicationDb
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "5031:3306"
      
  web:
    container_name: web-app-calculator-2
    hostname: app
    build: ./
    ports:
      - "5011:5011"
    depends_on:
      - mariadb
