// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _11_Calculator;

#nullable disable

namespace _11_Calculator.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250507072231_m_init")]
    partial class m_init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_11_Calculator.CalcModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Num1")
                        .HasColumnType("double");

                    b.Property<double>("Num2")
                        .HasColumnType("double");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<double>("Result")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.ToTable("CalcModels");
                });
#pragma warning restore 612, 618
        }
    }
}
